sudo: required
services:
    - docker

before_install:
    - docker build -t learndocker/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true learndocker/docker-react npm run test -- --coverage
